import { DQuestionFiled } from '../../../model/dQuestion';
// list
export const FILEDS: DQuestionFiled[] = [
 
    { id: 'fistName', label: 'First Name', value: '' },
    { id: 'middleName', label: 'Middle Name', value: '' },
    { id: 'lastName', label: 'Last Name', value: '' },
    { id: 'birthFirstName', label: 'Birth First Name', value: '' },
    { id: 'birthMiddleName', label: 'Birth Middle Name', value: '' },
    { id: 'birthLastName', label: 'Birth Last Name', value: '' },
    { id: 'employer', label: 'Employer', value: '' },
    { id: 'jobTitle', label: 'Job Title', value: '' },
    { id: 'workLocations', label: 'Work Locations', value: '' },
    { id: 'salary', label: 'Salary', value: '' },
    { id: 'spouseBirthCity', label: 'Spouse Birth City', value: '' },
    { id: 'spouseBirthState', label: 'Spouse Birth State', value: '' },
    { id: 'spouseBirthCountry', label: 'Spouse Birth Country', value: '' },
    { id: 'spouseCitizenship', label: 'Spouse Citizen Ship', value: '' },
    { id: 'spouseCountryNationality', label: 'Spouse Country Nationality', value: '' },
    { id: 'spousePassportNum', label: 'Spouse Passport Number', value: '' },
    { id: 'spousePassportPlace', label: 'Spouse Passport Place', value: '' },
    { id: 'spouseSsn', label: 'Spouse Ssn', value: '' },
    { id: 'spouseAlienNum', label: 'Spouse Alien Number', value: '' },
    { id: 'fatherResidenceCity', label: 'Father Residence City', value: '' },
    { id: 'fatherResidenceCountry', label: 'Father Residence Country', value: '' },
    { id: 'fatherEmployed', label: 'Father Employed', value: '' },
    { id: 'spouseLastName', label: 'Spouse Last Name', value: '' },
    { id: 'spouseFirstName', label: 'Spouse First Name', value: '' },
    { id: 'spouseMiddleName', label: 'Spouse Middle Name', value: '' },
    { id: 'spouseMaidenName', label: 'Spouse Maiden Name', value: '' },
    { id: 'spouseImmigrationStatus', label: 'Spouse Immigration Status', value: '' },
    { id: 'arrivalUSLastEntryPlace1', label: 'Arrival US Last Entry Place1', value: '' },
    { id: 'arrivalUSLastEntryPlace2', label: 'Arrival US Last Entry Place2', value: '' },
    { id: 'arrivalUSLastEntryStatus', label: 'Arrival US Last Entry Status', value: '' },
    { id: 'countryIssuance', label: 'Country Issuance', value: '' },
    { id: 'marriageStatus', label: 'Marriage Status', value: '' },
    { id: 'everInUS', label: 'Ever In US', value: '' },
    { id: 'marriageStartPlace', label: 'Marriage Start Place', value: '' },
    { id: 'motherLastName', label: 'Mother Last Name', value: '' },
    { id: 'motherFirstName', label: 'Mother First Name', value: '' },
    { id: 'motherMiddleName', label: 'Mother Middle Name', value: '' },
    { id: 'motherMaidenName', label: 'Mother Maiden Name', value: '' },
    { id: 'motherBirthCity', label: 'Mother Birth City', value: '' },
    { id: 'motherBirthCountry', label: 'Mother Birth Country', value: '' },
    { id: 'passportPlace', label: 'Passport Place', value: '' },
    { id: 'travelDocumentNumber', label: 'Travel Document Number', value: '' },
    { id: 'visaType', label: 'Visa Type', value: '' },
    { id: 'elisnum', label: 'Elis Number', value: '' },
    { id: 'I94Num', label: 'I94 Numeber', value: '' },
    { id: 'I94FullName', label: 'I94 Full Name', value: '' },
    { id: 'passportNum', label: 'Passport Number', value: '' },
    { id: 'addressMailingInCareOf', label: 'Address Mailing In CareOf ', value: '' },
    { id: 'addressMailingBldType', label: 'Address Mailing By Id Type', value: '' },
    { id: 'addressMailingNum', label: 'Address Mailing Number', value: '' },
    { id: 'addressMailingCity', label: 'Address Mailing City', value: '' },
    { id: 'addressMailingProvince', label: 'Address Mailing Province', value: '' },
    { id: 'addressMailingCounty', label: 'Address Mailing County', value: '' },
    { id: 'addressMailingState', label: 'Address Mailing State', value: '' },
    { id: 'addressMailingZip', label: 'Address Mailing Zip', value: '' },
    { id: 'addressMailingPostal', label: 'Address Mailing Postal', value: '' },
    { id: 'birthCity', label: 'Birth City', value: '' },
    { id: 'birthState', label: 'Birth State', value: '' },
    { id: 'birthProvince', label: 'Birth Province', value: '' },
    { id: 'birthCountry', label: 'Birth Country', value: '' },
    { id: 'ssn', label: 'SSN', value: '' },
    { id: 'alienNum', label: 'Alien Number', value: '' },
    { id: 'addressMainInCareOf', label: 'Address Main In CareOf', value: '' },
    { id: 'addressMainStreet', label: 'Address Main Street', value: '' },
    { id: 'addressMainBldType', label: 'Address Main By Id Type', value: '' },
    { id: 'addressMainNumber', label: 'Address Main Number', value: '' },
    { id: 'addressMainCity', label: 'Address Main City', value: '' },
    { id: 'addressMainProvince', label: 'Address Main Province', value: '' },
    { id: 'addressMainCounty', label: 'Address Main County', value: '' },
    { id: 'addressMainState', label: 'Address Main State', value: '' },
    { id: 'addressMainZip', label: 'Address Main Zip', value: '' },
    { id: 'addressMainPostal', label: 'Address Main Postal', value: '' },
    { id: 'phonePrimary', label: 'Phone Primary', value: '' },
    { id: 'phonePrimaryExt', label: 'Phone Primary Ext', value: '' },
    { id: 'phoneMobile', label: 'Phone Mobile', value: '' },
    { id: 'phoneHome', label: 'Phone Home', value: '' },
    { id: 'phoneEmergency', label: 'Phone Emergency', value: '' },
    { id: 'emergencyContactName', label: 'Emergency Contact Name', value: '' },
    { id: 'emergencyContactRelation', label: 'Emergency Contact Relation', value: '' },
    { id: 'otherName', label: 'Other Names', value: '' },
    { id: 'namebirth', label: 'Name at Birth', value: '' }
];

